### PR TITLE
Update to Minecraft 1.19

### PR DESCRIPTION
**Pull request by rutgerkok**
I saw on Discord (support channel) that you didn't have access to your PC, so I thought: let's update this thing myself! 🙂 The plugin should now work on Paper 1.19. Or at least, it does on my PC.

### CODE REVIEW

**Comment by alezhshede** [comment]
I probably should not comment here, but is there any chance i could get the 1.19 build?

**Comment by rutgerkok** [comment]
Yeah I can compile it for you. However, it seems like I can't upload JARs directly to Github, so here's a ZIP file containing the JAR:

[Pl3xMap.zip](https://github.com/NeumimTo/Pl3xMap/files/8933302/Pl3xMap.zip)

**Comment by alezhshede** [comment]
Thank you!

> Yeah I can compile it for you. However, it seems like I can't upload JARs directly to Github, so here's a ZIP file containing the JAR:
> 
> [Pl3xMap.zip](https://github.com/NeumimTo/Pl3xMap/files/8933302/Pl3xMap.zip)

**Comment by NeumimTo** [comment]
Seems ok, thanks for help.

**Pull request merged**
