### PR TITLE
Update to Minecraft 1.19.3

### PR DESCRIPTION
**Pull request by rutgerkok**
I'm not sure if you're still updating this thing, but I managed to update it to Minecraft 1.19.3.

(I couldn't find the location of the API of the new Pl3xmap, and it also seems to be missing the settings to limit the render area, so I haven't switched over yet to that version.)

### CODE REVIEW

**Comment by NeumimTo** [comment]
Hello, thanks for br but its kind of useless. 

Original author of pl3xmap has remade the plugin from scratch. Theres no reason to continue updating this fork. 

https://modrinth.com/plugin/pl3xmap

**Comment by rutgerkok** [comment]
Yeah, at some point I will switch, but right now I couldn't get Gradle to download the new Pl3xmap API, and the visibility limits seemed to be missing too.

**Comment by Roan-V** [comment]
Make a feature request over there :)

**Comment by rutgerkok** [comment]
Last time it was me who added that feature, so I think I'll have to code it again. 😝

**Pull request closed without merging**
